site_name: GENG Wei's Homepage
site_description: Wei GENG's personal webpage.
site_author: "Wei GENG"
docs_dir: docs/
repo_name: "vigeng/vigeng.github.io"
repo_url: "https://github.com/ViGeng/vigeng.github.io"
nav:
  - Home: index.md
  # - Blog: https://rowanblog.notion.site/

theme:
  name: material
  logo: figures/favicon.png
  # custom_dir: overrides
  # custom_dir: material/.overrides
  # font:
  # text: Bitter
  #   code: Roboto Mono
  # icon:
  # logo: material/library
  # admonition:
  # <type>: material/file-alert-outline

  favicon: figures/favicon.png
  palette:
    #primary: blue grey
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue grey # 上方的
      accent: teal # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: Switch to Dark Theme # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Theme
  features:
    - navigation.instant #- header.autohide  #自动隐藏
    - navigation.instant.prefetch
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.path
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view

copyright: Copyright &copy; 2022~2025 Wei GENG /All Rights Reserved. # 左下角的版权声明

extra:
  generator: false #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/WGeng_
    - icon: fontawesome/brands/github
      link: https://github.com/ViGeng
    - icon: fontawesome/regular/envelope
      link: mailto:<wei.geng@tum.de> #联系方式
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wegeng
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0001-5970-3550
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Wei-Geng-9
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=Zq6m2CIAAAAJ&hl=en
  analytics:
    provider: google
    property: G-3K0WBLE30D
  meta:
    robots: noindex, nofollow

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  # - blog:
  #     blog_dir: .
  #     post_dir: posts
  #     post_url_format: "{slug}"
  #     categories_allowed:
  #       - Publications
  #       - Teaching
  #       - Projects
  - tags
  - offline
  - search

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件


  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: "\ue157"

# extra_javascript:
# - javascripts/extra.js
# - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
# - javascripts/mathjax.js
# - https://polyfill.io/v3/polyfill.min.js?features=es6
# - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
# - ckplayer/js/ckplayer.js
# - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/js/social-share.min.js
# - javascripts/backgroud.js
# - javascripts/rellax.min.js
# - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js
extra_css:
  - stylesheets/extra.css
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/extra.css # extra.css的CDN
  # - stylesheets/extra1.css
  # - stylesheets/video.css
  # - https://unpkg.com/@waline/client@v2/dist/waline.css
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css
  # - ckplayer/css/ckplayer.css
  # - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
